[package]
name = "peckish"
version = "0.0.1"
description = "Create, manipulate, and transform Linux package formats!"
license = "Apache-2.0"
edition = "2021"
readme = "README.md"
categories = ["command-line-utilities", "development-tools", "filesystem"]
keywords = ["packages", "linux", "deb", "tarball", "docker"]

[dependencies]
anyhow = "1.0.70"
ar = "0.9.0"
async-recursion = "1.0.4"
async-trait = "0.1.67"
bollard = { git = "https://github.com/queer/bollard", rev = "628400c" }
brotli = "3.3.4"
clap = { version = "4.2.4", features = ["derive"] }
color-eyre = { version = "0.6.2", features = ["issue-url"] }
cpio_reader = "0.1.1"
ctor = "0.1.26"
eyre = "0.6.8"
flate2 = "1.0.25"
futures-util = "0.3.28"
hyper = "0.14.26"
indoc = "2.0.1"
itertools = "0.10.5"
md5 = "0.7.0"
nix = "0.26.2"
rand = "0.8.5"
regex = "1.8.1"
rpm = { git = "https://github.com/rpm-rs/rpm.git", rev = "cf4ef5c", features = ["with-file-async-tokio"] }
rsfs-tokio = { git = "https://github.com/queer/rsfs-tokio", rev = "55efcfa" }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
tokio-stream = "0.1.14"
tokio-tar = { git = "https://github.com/vorot93/tokio-tar", rev = "1bd30fbd1a219e8982571da48eb68f34317d1e15" }
tokio-util = { version = "0.7.8", features = ["codec"] }
tracing = "0.1.38"
tracing-subscriber = { version = "0.3.17", features = ["serde", "serde_json", "tracing", "env-filter", "fmt", "std"] }
xz2 = "0.1.7"
zstd = "0.12.3"

[profile.release]
opt-level = 3
lto = true
