[package]
name = "peckish"
version = "0.0.6"
description = "Create, manipulate, and transform Linux package formats!"
license = "Apache-2.0"
edition = "2021"
readme = "README.md"
categories = ["command-line-utilities", "development-tools", "filesystem"]
keywords = ["packages", "linux", "deb", "tarball", "docker"]

[dependencies]
anyhow = "1.0.71"
async-recursion = "1.0.4"
async-trait = "0.1.71"
bollard = { git = "https://github.com/queer/bollard", rev = "2624ced" }
clap = { version = "4.3.11", features = ["derive"] }
color-eyre = { version = "0.6.2", features = ["issue-url"] }
ctor = "0.2.3"
disk-drive = "0.1.10"
eyre = "0.6.8"
flail = "0.2.37"
flop = "0.2.4"
floppy-disk = "0.2.5"
hyper = "0.14.27"
indoc = "2.0.2"
itertools = "0.11.0"
md5 = "0.7.0"
nyoom = "0.3.5"
rand = "0.8.5"
regex = "1.9.0"
rpm = { version = "0.11.0" }
serde = { version = "1.0.168", features = ["derive"] }
serde_json = "1.0.100"
serde_yaml = "0.9.22"
smoosh = "0.2.0"
thiserror = "1.0.43"
tokio = { version = "1.29.0", features = ["full"] }
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.8", features = ["codec"] }
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.17", features = ["serde", "serde_json", "tracing", "env-filter", "fmt", "std"] }

[profile.release]
# debug = true
opt-level = 3
lto = true
