metadata:
  name: "peckish"
  version: "0.0.1-1"
  description: "peckish transforms software artifacts"
  author: "amy"
  arch: "amd64"
  license: "Apache-2.0"

input:
  name: "tarball"
  type: "tarball"
  path: "./examples/data/example.tar.Zstd"

output:
  - name: "files"
    type: "file"
    path: "./test_output_pls_ignore"
