metadata:
  name: "peckish"
  version: "0.0.1-1"
  description: "peckish transforms software artifacts"
  author: "amy"
  arch: "amd64"
  license: "Apache-2.0"

input:
  name: "peckish release binary"
  type: "file"
  paths:
    - "./target/x86_64-unknown-linux-musl/release/peckish"

output:
  - name: "queer/peckish:latest docker image"
    type: "docker"
    image: "queer/peckish:latest"
    base_image: "ubuntu:latest"
    entrypoint: ["/usr/bin/peckish"]
    injections:
      - type: "move"
        src: "/target/x86_64-unknown-linux-musl/release/peckish"
        dest: "/usr/bin/peckish"
