metadata:
  name: "hello-world"
  version: "0.0.1-1"
  description: "Hello, world!"
  author: "amy"
  arch: "amd64"
  license: "Apache-2.0"

input:
  name: "hello-world"
  type: "docker"
  image: "hello-world:latest"

output:
  - name: "ext image!!!"
    type: "ext4"
    path: "./out/ci/hello-world.ext4"
