chain: true

metadata:
  name: "peckish"
  version: "0.0.1-1"
  description: "peckish transforms software artifacts"
  author: "amy"
  arch: "amd64"
  license: "Apache-2.0"

input:
  name: "ubuntu"
  type: "docker"
  image: "ubuntu:latest"

output:
  - name: "tarball"
    type: "tarball"
    path: "./out/ci/ubuntu.docker.tar"
  - name: "wtf.docker"
    type: docker
    image: "wtf-ubuntu:latest"
