name: "Validate autocompression functionality"
on:
  push:
    branches:
      - "mistress"
    paths:
      - "**.rs"
      - "**.yaml"
      - "**.toml"
  pull_request:
    branches:
      - "mistress"
    paths:
      - "**.rs"
      - "**.yaml"
      - "**.toml"
jobs:
  run-autocompress-functionality-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          profile: "minimal"
          override: true
          target: "x86_64-unknown-linux-musl"
      - uses: "Swatinem/rust-cache@v2"
        with:
          key: "cli-functionality"
          cache-on-failure: true
      - name: "Install musl-tools"
        run: "sudo apt-get update && sudo apt-get install -y musl-tools comerr-dev wget"
      - name: "Install supported e2fs version"
        run: "wget -O e2fs-base.deb http://http.us.debian.org/debian/pool/main/e/e2fsprogs/libext2fs2_1.47.0-2_amd64.deb && wget -O e2fs.deb http://http.us.debian.org/debian/pool/main/e/e2fsprogs/libext2fs-dev_1.47.0-2_amd64.deb && sudo sudo sudo sudo sudo sudo sudo sudo dpkg -i e2fs-base.deb e2fs.deb"
      - name: "Build release binary!"
        uses: "actions-rs/cargo@v1"
        with:
          command: "build"
          args: "--release --target=x86_64-unknown-linux-musl"
      - name: "Run release binary"
        run: "pwd && ls -lah && env RUST_LOG=debug ./target/x86_64-unknown-linux-musl/release/peckish -c ./test-configs/peckish.autocompress.yaml"
      - name: "Validate tarball extraction"
        run: "ls -lah ./test_output_pls_ignore"
