name: "Validate CLI functionality"
on:
  push:
    branches:
      - "mistress"
  pull_request:
    branches:
      - "mistress"

jobs:
  run-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          override: true
      - name: "Release build"
        uses: "actions-rs/cargo@v1"
        with:
          command: "build"
          args: "--release"
      - name: "Run release binary"
        run: "./target/release/peckish"
      - name: "Validate release binary"
        run: "file ./target/release/peckish | grep 'ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped'"
      - name: "Validate Arch package"
        run: 'docker run --rm -it -v "./release/peckish.arch.pkg.tar:/app/peckish.pkg.tar" archlinux:latest pacman --noconfirm -U /app/peckish.pkg.tar'
      - name: "Validate Debian package"
        run: 'docker run --rm -it -v "./release/peckish.deb:/app/peckish.deb" debian:latest dpkg -i /app/peckish.deb'
      - name: "Validate tarball"
        run: "tar t -vf ./release/peckish.tar"
