name: "Docs: File"
on:
  pull_request:
    branches:
      - "mistress"
    paths:
      - "src/artifact/file.rs"

jobs:
  docs-file:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marocchino/sticky-pull-request-comment@v2"
        with:
          header: "File packages"
          message: "Don't forget to update the file docs!"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
