name: "Docs: Tarball"
on:
  pull_request:
    branches:
      - "mistress"
    paths:
      - "src/artifact/tarball.rs"

jobs:
  docs-tarball:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marocchino/sticky-pull-request-comment@v2"
        with:
          header: "Tarball packages"
          message: "Don't forget to update the tarball docs!"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
