name: "Docs: RPM"
on:
  pull_request:
    branches:
      - "mistress"
    paths:
      - "src/artifact/rpm.rs"

jobs:
  docs-rpm:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marocchino/sticky-pull-request-comment@v2"
        with:
          header: "RPM packages"
          message: "Don't forget to update the RPM docs!"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
