name: "Function: Host paths"
on:
  push:
    branches:
      - "mistress"
    paths:
      - "**.rs"
      - "**.yaml"
      - "**.toml"
  pull_request:
    branches:
      - "mistress"
    paths:
      - "**.rs"
      - "**.yaml"
      - "**.toml"
jobs:
  function-host-paths:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          profile: "minimal"
          override: true
          target: "x86_64-unknown-linux-musl"
      - uses: "Swatinem/rust-cache@v2"
        with:
          key: "host-file-dir-functionality"
          cache-on-failure: true
      - name: "Install musl-tools"
        run: "sudo apt-get update && sudo apt-get install -y musl-tools comerr-dev wget"
      - name: "Build release binary!"
        uses: "actions-rs/cargo@v1"
        with:
          command: "build"
          args: "--release --target=x86_64-unknown-linux-musl"
      - name: "Run release binary"
        run: "pwd && ls -lah && env RUST_LOG=debug ./target/x86_64-unknown-linux-musl/release/peckish -c ./configs/ci/peckish.host-file-dir.yaml"
      - name: "Validate file contents"
        run: "tar -tvf ./out/ci/host_file_dir.tar | grep hosts2"
      - name: "Validate directory contents"
        run: "tar -tvf ./out/ci/host_file_dir.tar | grep docs2"
