name: "Run cargo machete"
on:
  push:
    branches:
      - "mistress"
    paths:
      - "**.rs"
      - "**.toml"
  pull_request:
    branches:
      - "mistress"
    paths:
      - "**.rs"
      - "**.toml"

jobs:
  run-cargo-machete:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          override: true
      - name: "Install musl-tools"
        run: "sudo apt-get update && sudo apt-get install -y musl-tools comerr-dev wget"
      - name: "Install cargo-machete"
        run: "cargo install cargo-machete"
      - uses: "Swatinem/rust-cache@v1"
        with:
          key: "cargo-machete"
      - name: "Run cargo-machete"
        run: "cargo machete"
