name: "Quality: Formatting"
on:
  push:
    branches:
      - "mistress"
    paths:
      - "**.rs"
  pull_request:
    branches:
      - "mistress"
    paths:
      - "**.rs"

jobs:
  quality-formatting:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          override: true
          components: "rustfmt"
      - name: "Install musl-tools"
        run: "sudo apt-get update && sudo apt-get install -y musl-tools comerr-dev wget"
      - uses: "Swatinem/rust-cache@v2"
        with:
          key: "format"
      - name: "Run tests"
        run: "cargo fmt --all --check"
