name: "Quality: Docs"
on:
  push:
    branches:
      - "mistress"
    paths:
      - "**.rs"
  pull_request:
    branches:
      - "mistress"
    paths:
      - "**.rs"

jobs:
  quality-docs:
    strategy:
      matrix:
        version: ["stable", "1.70", "nightly"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "${{ matrix.version }}"
          override: true
      - name: "Install musl-tools"
        run: "sudo apt-get update && sudo apt-get install -y musl-tools comerr-dev wget"
      - uses: "Swatinem/rust-cache@v2"
        with:
          key: "doc"
      - name: "Run cargo doc"
        run: "cargo doc --workspace --all-features --examples --no-deps --locked"
