name: "Quality: Tests"
on:
  push:
    branches:
      - "mistress"
    paths:
      - "**.rs"
      - "Cargo.toml"
  pull_request:
    branches:
      - "mistress"
    paths:
      - "**.rs"
      - "Cargo.toml"

jobs:
  quality-tests:
    strategy:
      matrix:
        version: ["stable", "nightly", "1.71"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "${{ matrix.version }}"
          override: true
          profile: "minimal"
      - name: "Install musl-tools"
        run: "sudo apt-get update && sudo apt-get install -y musl-tools comerr-dev wget"
      - name: "paranoia"
        run: "rm -rfv ./out/ ./release/"
      - uses: "Swatinem/rust-cache@v2"
        with:
          key: "test"
      - name: "Run tests"
        run: "cargo test"
