name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.*"

jobs:
  create-release:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          profile: "minimal"
          target: "x86_64-unknown-linux-musl"
      - uses: "Swatinem/rust-cache@v2"
        with:
          key: "release"
          cache-on-failure: true
      - name: "Install musl-tools"
        run: "sudo apt-get update && sudo apt-get install -y musl-tools wget"
      - name: "Install supported e2fs version"
        run: "wget -O e2fs-base.deb http://http.us.debian.org/debian/pool/main/e/e2fsprogs/libext2fs2_1.47.0-2_amd64.deb && wget -O e2fs.deb http://http.us.debian.org/debian/pool/main/e/e2fsprogs/libext2fs-dev_1.47.0-2_amd64.deb && sudo dpkg -i e2fs-base.deb e2fs.deb"
      - name: "Build static-linked release binary!"
        uses: "actions-rs/cargo@v1"
        with:
          command: "build"
          args: "--release --target=x86_64-unknown-linux-musl"
      - name: "Package peckish!!"
        run: "./target/x86_64-unknown-linux-musl/release/peckish -c ./peckish.release.yaml -r report.txt"
      - name: "Create release"
        uses: "softprops/action-gh-release@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Upload release assets with gh cli"
        run: "cat report.txt | xargs -I {} gh release upload ${{ github.ref_name }} {}"
        env:
          GH_TOKEN: ${{ github.token }}
